export interface Film {
  id: string;
  tmdbId: number;
  title: string;
  year: number;
  posterUrl: string | null;
  backdropUrl: string | null;
  overview: string | null;
  runtime: number | null;
  director: string | null;
  tmdbRating: number | null;
  isOscarWinner: boolean;
  genre: string;
  decade: string;
}

export const FILMS: Film[] = [
  {
    id: "the-godfather",
    tmdbId: 238,
    title: "The Godfather",
    year: 1972,
    posterUrl: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/rSPw7WgCHbRrFYjVePIbUjGgFWW.jpg",
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family.",
    runtime: 175,
    director: "Francis Ford Coppola",
    tmdbRating: 8.7,
    isOscarWinner: true,
    genre: "Drama",
    decade: "1970s",
  },
  {
    id: "the-dark-knight",
    tmdbId: 155,
    title: "The Dark Knight",
    year: 2008,
    posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW1Warb1XZHRFiSsEifwqFHE.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/nMKdUZphdQk58LjlLVKqFq0DhHY.jpg",
    overview: "Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and District Attorney Harvey Dent.",
    runtime: 152,
    director: "Christopher Nolan",
    tmdbRating: 8.5,
    isOscarWinner: true,
    genre: "Action",
    decade: "2000s",
  },
  {
    id: "pulp-fiction",
    tmdbId: 680,
    title: "Pulp Fiction",
    year: 1994,
    posterUrl: "https://image.tmdb.org/t/p/w500/d5iIl40f9vCNlbGanyiASq9JKaY.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/suaEOkG2xqZV5pgFiHh7Z1q3yz8.jpg",
    overview: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    runtime: 154,
    director: "Quentin Tarantino",
    tmdbRating: 8.5,
    isOscarWinner: true,
    genre: "Drama",
    decade: "1990s",
  },
  {
    id: "inception",
    tmdbId: 27205,
    title: "Inception",
    year: 2010,
    posterUrl: "https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/oIZiWsidM1l8uKAhepSxgkmF8xB.jpg",
    overview: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.",
    runtime: 148,
    director: "Christopher Nolan",
    tmdbRating: 8.4,
    isOscarWinner: false,
    genre: "Sci-Fi",
    decade: "2010s",
  },
  {
    id: "the-silence-of-the-lambs",
    tmdbId: 274,
    title: "The Silence of the Lambs",
    year: 1991,
    posterUrl: "https://image.tmdb.org/t/p/w500/uS9m8OB0BMYR4Dm4qtxSGXI0U1G.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/hgGUby1JvKNOj2wO3vS46yqXPv.jpg",
    overview: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
    runtime: 118,
    director: "Jonathan Demme",
    tmdbRating: 8.2,
    isOscarWinner: true,
    genre: "Thriller",
    decade: "1990s",
  },
  {
    id: "fight-club",
    tmdbId: 550,
    title: "Fight Club",
    year: 1999,
    posterUrl: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4rQ6ofnAz.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkqSbbzPV.jpg",
    overview: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    runtime: 139,
    director: "David Fincher",
    tmdbRating: 8.4,
    isOscarWinner: false,
    genre: "Drama",
    decade: "1990s",
  },
  {
    id: "forrest-gump",
    tmdbId: 13,
    title: "Forrest Gump",
    year: 1994,
    posterUrl: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVf6blMFCY8T3XZy.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/3hRMVHJVMTqCtVF8Aqs6mcVPUST.jpg",
    overview: "The presidencies of Kennedy and Johnson, the Vietnam War, and other events unfold through the perspective of an Alabama man.",
    runtime: 142,
    director: "Robert Zemeckis",
    tmdbRating: 8.5,
    isOscarWinner: true,
    genre: "Drama",
    decade: "1990s",
  },
  {
    id: "gladiator",
    tmdbId: 98,
    title: "Gladiator",
    year: 2000,
    posterUrl: "https://image.tmdb.org/t/p/w500/ty8TGRysJL9jDQ0kDzMUKEKdhPY.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/adA3260a9yiNg9M31UpPptr4V0b.jpg",
    overview: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    runtime: 155,
    director: "Ridley Scott",
    tmdbRating: 8.2,
    isOscarWinner: true,
    genre: "Action",
    decade: "2000s",
  },
  {
    id: "the-matrix",
    tmdbId: 603,
    title: "The Matrix",
    year: 1999,
    posterUrl: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/fy N97GTeWRKMFz3XoQ6elwbjnV.jpg",
    overview: "A computer hacker learns that reality as he knows it is a simulation created by machines, and joins a rebellion to free humanity.",
    runtime: 136,
    director: "The Wachowskis",
    tmdbRating: 8.2,
    isOscarWinner: false,
    genre: "Sci-Fi",
    decade: "1990s",
  },
  {
    id: "interstellar",
    tmdbId: 157336,
    title: "Interstellar",
    year: 2014,
    posterUrl: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/rAiYTfKGqExCRIxHSEqVx3Q7Dcq.jpg",
    overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    runtime: 169,
    director: "Christopher Nolan",
    tmdbRating: 8.4,
    isOscarWinner: false,
    genre: "Sci-Fi",
    decade: "2010s",
  },
  {
    id: "the-shawshank-redemption",
    tmdbId: 278,
    title: "The Shawshank Redemption",
    year: 1994,
    posterUrl: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryQ3awq2NdC9.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/kXfqcdQKsIn4FZiWov1g6YWia6U.jpg",
    overview: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    runtime: 142,
    director: "Frank Darabont",
    tmdbRating: 8.7,
    isOscarWinner: false,
    genre: "Drama",
    decade: "1990s",
  },
  {
    id: "schindlers-list",
    tmdbId: 424,
    title: "Schindler's List",
    year: 1993,
    posterUrl: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIayr2.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/loRmRzqo5nWaAfMmE4KqJj5SLoZ.jpg",
    overview: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.",
    runtime: 195,
    director: "Steven Spielberg",
    tmdbRating: 8.6,
    isOscarWinner: true,
    genre: "Drama",
    decade: "1990s",
  },
  {
    id: "the-lord-of-the-rings",
    tmdbId: 122,
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    posterUrl: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjAFfLlufPTL4Vw.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/pm0RiwNpSj8ERoQVB6mB1QqKPPj.jpg",
    overview: "Gandalf and Aragorn lead the World of the Wizards against Sauron's army to reclaim Gondor.",
    runtime: 201,
    director: "Peter Jackson",
    tmdbRating: 8.5,
    isOscarWinner: true,
    genre: "Action",
    decade: "2000s",
  },
  {
    id: "goodfellas",
    tmdbId: 103,
    title: "Goodfellas",
    year: 1990,
    posterUrl: "https://image.tmdb.org/t/p/w500/aKuFiU1sLR3URJHWmAN5en2bF7C.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/sw7mordbZxgITU877yTpZCud90M.jpg",
    overview: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen and his mob partners.",
    runtime: 146,
    director: "Martin Scorsese",
    tmdbRating: 8.5,
    isOscarWinner: false,
    genre: "Drama",
    decade: "1990s",
  },
  {
    id: "se7en",
    tmdbId: 807,
    title: "Se7en",
    year: 1995,
    posterUrl: "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/rUQL6P4L1NluLkUl3rBdj9UDqQH.jpg",
    overview: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    runtime: 127,
    director: "David Fincher",
    tmdbRating: 8.4,
    isOscarWinner: false,
    genre: "Thriller",
    decade: "1990s",
  },
  {
    id: "saving-private-ryan",
    tmdbId: 4613,
    title: "Saving Private Ryan",
    year: 1998,
    posterUrl: "https://image.tmdb.org/t/p/w500/uqx37cS8cpNi8vPOF2PYQIV5B6Q.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/z6mHFnVYF8VUhUcJdBTV3pn6V4j.jpg",
    overview: "After the Normandy landings, a group of soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed.",
    runtime: 169,
    director: "Steven Spielberg",
    tmdbRating: 8.5,
    isOscarWinner: false,
    genre: "Action",
    decade: "1990s",
  },
  {
    id: "the-departed",
    tmdbId: 1422,
    title: "The Departed",
    year: 2006,
    posterUrl: "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/l6NnWDe8WKtJgh9TLm8rsRKJ3U3.jpg",
    overview: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
    runtime: 151,
    director: "Martin Scorsese",
    tmdbRating: 8.2,
    isOscarWinner: true,
    genre: "Drama",
    decade: "2000s",
  },
  {
    id: "prestige",
    tmdbId: 1124,
    title: "The Prestige",
    year: 2006,
    posterUrl: "https://image.tmdb.org/t/p/w500/bdN3gWiGQH9l4PcUxqfY1xTPGv4.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/cIN3J7C2TaGWSqzrscJ6OTSoeol.jpg",
    overview: "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have.",
    runtime: 130,
    director: "Christopher Nolan",
    tmdbRating: 8.2,
    isOscarWinner: false,
    genre: "Thriller",
    decade: "2000s",
  },
  {
    id: "django-unchained",
    tmdbId: 64421,
    title: "Django Unchained",
    year: 2012,
    posterUrl: "https://image.tmdb.org/t/p/w500/7oWY8VDWW7rTzipsfAj8H44LXgi.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/7H5nw7w8udRwiqjlqeFwlv9oEKr.jpg",
    overview: "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a plantation owner in Mississippi.",
    runtime: 165,
    director: "Quentin Tarantino",
    tmdbRating: 8.2,
    isOscarWinner: true,
    genre: "Drama",
    decade: "2010s",
  },
  {
    id: "mad-max-fury-road",
    tmdbId: 76331,
    title: "Mad Max: Fury Road",
    year: 2015,
    posterUrl: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    backdropUrl: "https://image.tmdb.org/t/p/original/phszHPFVhPHhMZgo0fWTKBDQsJA.jpg",
    overview: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners.",
    runtime: 120,
    director: "George Miller",
    tmdbRating: 8.1,
    isOscarWinner: true,
    genre: "Action",
    decade: "2010s",
  },
];

export const FEATURED_FILMS = FILMS.filter((f) => f.isOscarWinner).slice(0, 6);

export const BADGES = [
  {
    slug: "first-film",
    name: "First Steps",
    description: "Watch your first film",
    icon: "Film",
    xpBonus: 0,
  },
  {
    slug: "ten-films",
    name: "Getting Started",
    description: "Watch 10 films",
    icon: "Play",
    xpBonus: 50,
  },
  {
    slug: "oscar-collector",
    name: "Oscar Collector",
    description: "Watch 5 Oscar-winning films",
    icon: "Award",
    xpBonus: 100,
  },
  {
    slug: "streak-7",
    name: "Week Warrior",
    description: "Maintain a 7-day watch streak",
    icon: "Flame",
    xpBonus: 75,
  },
  {
    slug: "cinema-scholar",
    name: "Cinema Scholar",
    description: "Watch films from 5 different decades",
    icon: "GraduationCap",
    xpBonus: 150,
  },
  {
    slug: "level-5",
    name: "Rising Star",
    description: "Reach Level 5",
    icon: "Star",
    xpBonus: 200,
  },
  {
    slug: "action-hero",
    name: "Action Hero",
    description: "Watch 5 Action films",
    icon: "Zap",
    xpBonus: 50,
  },
  {
    slug: "thriller-master",
    name: "Thriller Master",
    description: "Watch 5 Thriller films",
    icon: "Eye",
    xpBonus: 50,
  },
];

export const STREAMING_PLATFORMS = [
  { name: "Netflix", logo: "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg", url: "https://netflix.com" },
  { name: "Amazon Prime", logo: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Amazon_Prime_Logo.svg", url: "https://primevideo.com" },
  { name: "Apple TV+", logo: "https://upload.wikimedia.org/wikipedia/commons/2/28/Apple_TV_Plus_Logo.svg", url: "https://tv.apple.com" },
  { name: "Disney+", logo: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Disney%2B_logo.svg", url: "https://disneyplus.com" },
  { name: "Max", logo: "https://upload.wikimedia.org/wikipedia/commons/1/17/HBO_Max_Logo.svg", url: "https://max.com" },
];
